name: Deploy MERN App to VPS

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install dependencies and build the React app (frontend)
      - name: Install and build frontend
        run: |
          cd client
          npm install
          npm run build

      # Step 3: Deploy to VPS using SSH
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/Orange-cap-react
            git pull origin main

            # Install dependencies and build the React app (frontend)
            cd client
            npm install
            npm run build

            # Install dependencies for the backend (server)
            cd ../server
            npm install

            # Restart the backend using PM2
            pm2 restart project-backend